# Page settings

baseURL = "http://www.ryanthults.com/"
languageCode = "en"
title = "Ryan Hults | Senior Software Engineer"
theme = "hugo-devresume"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#500000"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ryan Hults"
        tagline = "Senior Software Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Fort Worth, Texas"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "405-345-6770"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "contact@ryanthults.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "ryanthults.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/React/Angular/Vue"
        [[params.skills.list.items]]
        details = "Python/PHP"
        [[params.skills.list.items]]
        details = "AWS/ECS/EC2"
        [[params.skills.list.items]]
        details = "Django"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Docker"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "Object-oriented design"

    
    

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Full-stack development"
        [[params.skills.list.items]]
        details = "Scaleable Cloud-based microservices"
        [[params.skills.list.items]]
        details = "Enterprise website management"
        [[params.skills.list.items]]
        details = "Agile project management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS in Eletronic Systems Engineering"
        university = "Texas A&M University"
        dates = "2016"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"








    [params.interests]
        enable = true
        details = "Climbing, 3d Modeling and Printing, Progressive Metal, DIY"

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "3d CAD and Printing"
        [[params.interests.list]]
        name = "Progressive Metal"
        [[params.interests.list]]
        name = "DIY/Home Automation"








    [params.summary]
        enable = true
        text = "With 7+ years of backend development experience and a passion for full-stack applications and DevOps, I specialize in building efficient, scalable systems. My work spans from greenfield architecting, to performance tuning, to infrastructure automation and beyond. I’m always focused on clean, maintainable code that delivers measurable impact. From defense systems to SaaS platforms, I thrive on solving complex technical challenges across the stack."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2021 - Present"
        company = "Monetate"
        details = "As a technical leader, I drove large-scale infrastructure improvements and cost-efficient optimizations while fostering cross-team collaboration to enhance system reliability and operational processes. My work involved modernizing legacy systems, mentoring engineers, and implementing best practices to elevate both technical output and organizational efficiency."
        [[params.experience.list.items]]
        details = "Led the planning and implementation of a major refactor of our AI product offering, reduced compute costs by over 20% and increasing client revenue per session by 30%. Managed team agile processes throughout the project."
        [[params.experience.list.items]]
        details = "Led the planning and execution of migrating critical components of the company’s codebase from Python 2 to Python 3, ensuring compatibility and minimal disruption."
        [[params.experience.list.items]]
        details = "Led cross-team initiatives to streamline and document critical processes, enhancing operational efficiency and knowledge sharing"
        [[params.experience.list.items]]
        details = "Guided junior engineers through Python best practices and system design, improving team code quality and output."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2018 - 2021"
        company = "L3Harris Link Simulation & Training"
        details = "In this role, I contributed to the development and optimization of high-fidelity real-time flight simulators, focusing on system reliability, performance tuning, and direct customer support. My work involved enhancing back-end infrastructure, resolving critical defects, and implementing distributed simulation architectures to ensure robust and efficient training systems."
        [[params.experience.list.items]]
        details = "Design, development and debugging of high-fidelity real-time F-18 simulator."
        [[params.experience.list.items]]
        details = "Provided on-site support and de-bugging while interacting directly with customers."
        [[params.experience.list.items]]
        details = "Improved back-end infrastructure to reduce complexity and coldstart times by 15%."
        [[params.experience.list.items]]
        details = "Worked on HLA, middleware logic, and MAK Logger interface"
        [[params.experience.list.items]]
        details = "Design and maintain a High-Level Architecture (HLA) Federate."
        [[params.experience.list.items]]
        details = "Fixed mission-critical bugs, including memory mismanagement issues and segmentation faults."

        [[params.experience.list]]
        title = "Student Technician"
        dates = "2014 - 2017"
        company = "Texas A&M University"
        details = "Provided comprehensive IT support by troubleshooting hardware and software issues, managing system deployments, and maintaining secure inventory workflows for academic and research environments."



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Realtime Content Rendering Service"
        meta = "Python, Amazon ECS, Puppeteer"
        tagline = "Created a scalable containerized microservice that dynamically generated client-configurable web content on-demand."

        [[params.projects.list]]
        title = "Zoom-to-Cloud Recording Backup"
        meta = "JSON, Python"
        tagline = "Python Application that downloads and organizes all cloud recordings from your Zoom Business account, with optional ability to upload the recordings to SharePoint. Uses Zoom Developer API and Microsoft GraphQL."

        [[params.projects.list]]
        title = "Internet of Cows"
        meta = "C, Node.JS, PHP, Python, SQL"
        tagline = "An Internet of Things wireless monitoring prototype for livestock."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, 3d Modeling and Printing, Progressive Metal, DIY"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/ryanthults"
        title = "ryanthults"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/rhults"
        title = "rhults"




